# Generated by Django 4.2.18 on 2025-03-03 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SentencePair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_sentence", models.TextField()),
                ("target_sentence", models.TextField()),
                ("source_language", models.CharField(max_length=10)),
                ("target_language", models.CharField(max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Alignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_indices", models.JSONField()),
                ("target_indices", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sentence_pair",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alignments",
                        to="api.sentencepair",
                    ),
                ),
            ],
        ),
    ]
